version: "3"
services:
  stratum:
    image: docker.io/grinpool/stratum:latest
    restart: always
    network_mode: "host"
    hostname: "stratum"
    environment:
      - redis_host=192.168.252.54
      - redis_port_base=0
      - s.diff_number=1
      - s.port=9101
      - api.port=9130
      - stratum_host=192.168.252.54
      - stratum_port=9200
      - stratum_api=13413
    ports:
      - "9101:9101"
  stratum10:
    image: docker.io/grinpool/stratum:latest
    restart: always
    network_mode: "host"
    hostname: "stratum10"
    environment:
      - redis_host=192.168.252.54
      - redis_port_base=3
      - s.diff_number=1
      - s.port=9110
      - api.port=9140
      - stratum_host=192.168.252.54
      - stratum_port=9200
      - stratum_api=13413
    ports:
      - "9111:9110"
