version: "3"
services:
  stratum:
    image: docker.io/grinpool/stratum:latest
    restart: always
    network_mode: "host"
    hostname: "stratum"
    environment:
      - redis_port_base=3
      - s.diff_number=1
      - s.port=9108
    ports:
      - "9108:9108"
